CSRCS := $(wildcard *.c)
CPPSRCS := $(wildcard *.cpp)
ASRCS := $(wildcard *.S)
COBJS := $(CSRCS:.c=.o)
CPPOBJS := $(CPPSRCS:.cpp=.o)
AOBJS := $(ASRCS:.S=.o)
AllOBJS := $(COBJS) $(CPPOBJS) $(AOBJS)
LOADADDR = 0x80000

COBKERNEL_VERBOSITY ?= VERBOSITY_INFO

GCCFLAGS = -mcpu=cortex-a76 -mlittle-endian -Wall -O0 -ffreestanding \
           -nostartfiles -nostdlib -nostdinc -g -I $(INCLUDE)

AFLAGS = -mcpu=cortex-a76 -mlittle-endian  -I $(INCLUDE) -O0 -g

CFLAGS = -mcpu=cortex-a76 -mlittle-endian -Wall -fsigned-char -ffreestanding -g \
         -I $(INCLUDE) -O0 -fno-exceptions  -DPRINTF_LONG_SUPPORT -D$(COBKERNEL_VERBOSITY)

CPPFLAGS = -fno-exceptions -fno-rtti -nostdinc++ -mcpu=cortex-a76 -mlittle-endian -Wall -fsigned-char \
			  -ffreestanding -g -I ./include -O0 -mstrict-align -std=c++14 -Wno-aligned-new \

%.o: %.S
	@echo "as $@"
	@gcc $(AFLAGS) -c $< -o $@

%.o: %.c
	@echo "gcc $@"
	@gcc $(CFLAGS) -c $< -o $@

%.o: %.cpp
	@echo "g++ $@"
	@g++ $(CPPFLAGS) -c $< -o $@