//
// config.h
//

#ifndef _config_h
#define _config_h

.equ MEGABYTE, 0x100000
.equ KILOBYTE, 0x400
.equ NUM_CORES, 4
.equ MEM_KERNEL_START, 0x80000 // Start address of the main program
.equ KERNEL_MAX_SIZE, (8 * MEGABYTE)
.equ MEM_KERNEL_END, (MEM_KERNEL_START + KERNEL_MAX_SIZE)
.equ KERNEL_STACK_SIZE, (8 * MEGABYTE)
.equ MEM_KERNEL_STACK, (MEM_KERNEL_END + KERNEL_STACK_SIZE)
.equ ARM_MMU_TABLE_BASE_LO, MEM_KERNEL_END + (NUM_CORES * KERNEL_STACK_SIZE)
.equ MMU_TABLE_SIZE, MEGABYTE
.equ ARM_MMU_TABLE_BASE_HI, ARM_MMU_TABLE_BASE_LO + MMU_TABLE_SIZE
//aligning heap end to a 64KB boundary
.equ HEAP_START, (ARM_MMU_TABLE_BASE_HI + MMU_TABLE_SIZE + 0x400*64) &  0xFFFFFFFFFFFF0000
.equ HEAP_END, 0x40000000

#endif
